#!/bin/bash

WORKSPACE="."
COMPILER_HOME="$WORKSPACE/sdk/PSEM2M-Compiler"

/usr/bin/python "$COMPILER_HOME/preprocessor.py" \
    --clean-after-build \
    -R "${WORKSPACE}/trunk" \
    -E "${WORKSPACE}/remote-services:${WORKSPACE}/demo-gif" \
    -T "${WORKSPACE}/platforms/felix" \
    --ipojo-ant-file="$COMPILER_HOME/org.apache.felix.ipojo.ant-1.9.0-SNAPSHOT.jar" \
    --ipojo-annotations="$COMPILER_HOME/org.apache.felix.ipojo.annotations-1.9.0-SNAPSHOT.jar"

