{
    "name":"DistributedHelloWorld",
    "components":[
        {
            "name":"snowball-compo",
            "type":"demo.consumer",
            "wires":{
                "provider":"central-compo"
            }
        },
        {
            "name":"central-compo",
            "type":"demo.provider"
        }
    ]
}