#!/bin/bash

export PYTHONPATH=$(pwd)

echo "Erase..."
coverage erase
rm -fr htmldoc 2>/dev/null

echo "Run..."

files=(ldapfilter pelix ipopo)

for i in ${files[@]}
do
	echo "Working on $i"
	coverage run --parallel-mode tests/${i}_test.py || exit 1
done

echo "Combine..."
coverage combine

echo "HTML..."
coverage html

echo "Done."
firefox-trunk ./htmlcov/index.html

