{
    "id":"gif.demo.data-server",
    "kind":"felix",
    "httpPort":9210,
    "vmArgs":[
        
    ],
    "bundles":[
        {
            "symbolicName":"org.psem2m.isolates.demo.services.ui.viewer",
            "optional":true,
            "properties":{
                "psem2m.demo.ui.viewer.top":"0.66scr",
                "psem2m.demo.ui.viewer.left":"0.333scr",
                "psem2m.demo.ui.viewer.width":"0.333scr",
                "psem2m.demo.ui.viewer.height":"0.33scr",
                "psem2m.demo.ui.viewer.color":"YellowGreen"
            }
        },
        {
            "symbolicName":"org.apache.felix.shell"
        },
        {
            "symbolicName":"org.apache.felix.shell.remote",
            "properties":{
                "osgi.shell.telnet.port":"6010"
            }
        },
        {
            "from":"signals-http.js"
        },
        {
            "from":"rose-core.js"
        },
        {
            "from":"rose-client.js"
        },
        {
            "from":"rose-server.js"
        },
        {
            "from":"remote-services.js"
        },
        {
            "symbolicName":"org.psem2m.demo.erp.api"
        },
        {
            "symbolicName":"org.psem2m.demo.data.cache"
        },
        {
            "symbolicName":"org.psem2m.demo.data.server"
        }
    ]
}