{
    "id":"psem2m.monitor",
    "kind":"felix",
    "bundles":[
        {
            "symbolicName":"org.apache.felix.shell",
        },
        {
            "symbolicName":"org.apache.felix.shell.remote"
        },
        {
            "symbolicName":"org.ow2.chameleon.commons.jabsorb"
        },
        {
            "symbolicName":"org.ow2.chameleon.rose.core",
        },
        {
            "symbolicName":"org.apache.felix.http.bundle",
        },
        {
            "symbolicName":"org.psem2m.remote.client.rose",
        },
        {
            "symbolicName":"jabsorb-client-factory"
        },
        {
            "symbolicName":"org.psem2m.isolates.remote.importer"
        },
        {
            "symbolicName":"org.psem2m.isolates.demo.services.ui.viewer",
            "optional":true
        },
        {
            "symbolicName":"org.psem2m.isolates.master.manager"
        },
        {
            "symbolicName":"org.psem2m.isolates.monitor"
        }
    ]
}