{
    "id":"org.psem2m.internals.isolates.monitor-1",
    "kind":"felix",
    "httpPort":9000,
    "bundles":[
        {
            "symbolicName":"org.psem2m.isolates.demo.services.ui.viewer",
            "optional":true
        },
        {
            "symbolicName":"org.apache.felix.shell"
        },
        {
            "symbolicName":"org.apache.felix.shell.remote"
        },
        {
            "from":"signals-http.js"
        },
        {
            "from":"rose-core.js"
        },
        {
            "from":"rose-client.js"
        },
        {
            "from":"rose-server.js"
        },
        {
            "from":"remote-services.js"
        },
        {
            "symbolicName":"org.psem2m.isolates.master.manager"
        },
        {
            "symbolicName":"org.psem2m.isolates.monitor"
        }
    ]
}