{
    "id":"psem2m.monitor",
    "kind":"felix",
    "bundles":[
        {
            "symbolicName":"org.psem2m.isolates.demo.services.ui.viewer",
            "optional":true
        },
        {
            "symbolicName":"org.apache.felix.shell"
        },
        {
            "symbolicName":"org.apache.felix.shell.remote"
        },
        {
            "from":"rose-core.js"
        },
        {
            "from":"rose-client.js"
        },
        {
            "symbolicName":"org.psem2m.isolates.remote.importer"
        },
        {
            "symbolicName":"org.psem2m.isolates.master.manager"
        },
        {
            "symbolicName":"org.psem2m.isolates.monitor"
        }
    ]
}