{
    "id":"org.psem2m.internals.isolates.forker",
    "kind":"felix",
    "bundles":[
        {
            "symbolicName":"org.psem2m.isolates.demo.services.ui.viewer",
            "optional":true
        },
        {
            "symbolicName":"org.apache.felix.shell"
        },
        {
            "symbolicName":"org.apache.felix.shell.remote"
        },
        {
            "from":"rose-core.js"
        },
        {
            "from":"rose-server.js"
        },
        {
            "symbolicName":"org.psem2m.isolates.remote.exporter"
        },
        {
            "symbolicName":"org.psem2m.isolates.forker"
        }
    ]
}