{
    "id":"org.psem2m.internals.isolates.forker",
    "kind":"felix",
    "httpPort":9001,
    "vmArgs":[
        "-Xms32M",
        "-Xmx56M"
    ],
    "bundles":[
        {
            "symbolicName":"org.apache.felix.shell"
        },
        {
            "symbolicName":"org.apache.felix.shell.remote",
            "properties":{
            	"osgi.shell.telnet.port":"6001"
            }
        },
        {
            "from":"signals-http.js"
        },
        {
            "from":"jsonrpc.js"
        },
        {
            "from":"remote-services.js"
        },
        {
            "symbolicName":"org.psem2m.isolates.forker"
        }
    ]
}