[
    {
        "symbolicName":"org.apache.felix.http.bundle"
    },
    {
        "symbolicName":"org.jabsorb.ng"
    },
    {
        "symbolicName":"org.psem2m.signals.serializer.json"
    },
    {
        "symbolicName":"org.psem2m.remote.jsonrpc"
    }
]