[
    {
        "symbolicName":"jabsorb-client-factory"
    },
    {
        "symbolicName":"org.apache.servicemix.bundles.commons-codec"
    },
    {
        "symbolicName":"commons-logging"
    },
    {
        "symbolicName":"org.apache.servicemix.bundles.commons-httpclient"
    },
    {
        "symbolicName":"org.psem2m.remote.client.rose"
    }
]