[
    {
        "symbolicName":"org.apache.felix.http.bundle"
    },
    {
        "symbolicName":"org.psem2m.signals.http"
    },
    {
        "symbolicName":"org.psem2m.signals.serializer.json"
    }
]