#!/bin/bash

cd boot/org.cohorte.pyboot
mvn deploy
sleep 6
cd -
cd boot/org.cohorte.pyboot.api
mvn deploy
sleep 6
cd -
cd boot/org.cohorte.pyboot.config
mvn deploy
sleep 6
cd -
cd boot/org.cohorte.pyboot.shell.agent
mvn deploy
sleep 6
cd -
cd boot/org.psem2m.isolates.base
mvn deploy
sleep 6
cd -
cd boot/org.psem2m.isolates.constants
mvn deploy
sleep 6
cd -
cd composer/org.cohorte.composer.api
mvn deploy
sleep 6
cd -
cd composer/org.cohorte.composer.isolate
mvn deploy
sleep 6
cd -
cd isolates/org.cohorte.shell.osgi
mvn deploy
sleep 6
cd -
cd isolates/org.cohorte.shell.remote
mvn deploy
sleep 6
cd -
cd isolates/org.psem2m.isolates.loggers
mvn deploy
sleep 6
cd -
cd isolates/org.psem2m.isolates.slave.agent
mvn deploy
sleep 6
cd -
cd isolates/org.psem2m.status.storage
mvn deploy
sleep 6
cd -
cd ui/org.psem2m.isolates.ui
mvn deploy
sleep 6
cd -
cd ui/org.psem2m.isolates.ui.admin
mvn deploy
sleep 6
cd -
cd cohorte-runtime-package
mvn deploy
sleep 6
cd -
