{
    "name":"demo.july2012",
    "components":[
        {
            "name":"temper-stratus",
            "type":"demo-temperature-fake-factory",
            "isolate":"isolate-stratus-temper",
            "properties":{
                "temper.value.min":-5,
                "temper.value.max":45
            }
        },
        {
            "name":"temper-raspberrypi",
            "type":"demo-temperature-fake-factory",
            "isolate":"isolate-raspberrypi-temper"
        },
        {
            "name":"temper-laptop",
            "type":"java-fake-temp-factory",
            "isolate":"isolate-laptop-temper"
        },
        {
            "name":"aggregator",
            "type":"demo-sensor-aggregator-factory",
            "isolate":"isolate-stratus-aggregator",
            "properties":{
                "poll.delta":1
            }
        },
        {
            "name":"aggregator-web",
            "type":"demo-sensor-aggregator-ui-factory",
            "isolate":"isolate-stratus-aggregator",
            "properties":{
                "servlet.path":"/sensors"
            },
            "wires":{
                "_aggregator":"aggregator"
            }
        }
    ]
}