{
    "id":"org.psem2m.internals.isolates.forker",
    "kind":"pelix",
    "node":"stratus",
    "httpPort":9001,
    "bundles":[
        {
            "symbolicName":"base.httpsvc"
        },
        {
            "symbolicName":"base.signals.directory"
        },
        {
            "symbolicName":"base.signals.directory_updater"
        },
        {
            "symbolicName":"base.signals.http"
        },
        {
            "symbolicName":"psem2m.forker.config_broker"
        },
        {
            "symbolicName":"psem2m.forker.core"
        },
        {
            "symbolicName":"psem2m.runner.java"
        },
        {
            "symbolicName":"psem2m.runner.python"
        },
        {
            "symbolicName":"psem2m.forker.heartbeat"
        },
        {
            "symbolicName":"psem2m.forker.cmd_agent"
        }
    ]
}