{
    "id":"org.psem2m.internals.isolates.monitor-2",
    "kind":"felix",
    "host":"10.130.1.96",
    "httpPort":7999,
    "vmArgs":[
        "-Xms32M",
        "-Xmx64M"
    ],
    "bundles":[
        {
            "symbolicName":"org.psem2m.isolates.ui.admin",
            "optional":true,
            "properties":{
                "psem2m.demo.ui.viewer.top":"0scr",
                "psem2m.demo.ui.viewer.left":"0scr",
                "psem2m.demo.ui.viewer.width":"0.25scr",
                "psem2m.demo.ui.viewer.height":"0.66scr",
                "psem2m.demo.ui.viewer.color":"SkyBlue"
            }
        },
        {
            "symbolicName":"org.apache.felix.shell"
        },
        {
            "symbolicName":"org.apache.felix.shell.remote",
            "properties":{
                "osgi.shell.telnet.port":"5999"
            }
        },
        {
            "from":"signals-http.js"
        },
        {
            "from":"rose-core.js"
        },
        {
            "from":"rose-client.js"
        },
        {
            "from":"rose-server.js"
        },
        {
            "from":"remote-services.js",
            "overriddenProperties":{
                    "org.psem2m.remote.filters.exclude":"*.demo.*"
            }
        },
        {
            "symbolicName":"org.psem2m.isolates.master.manager"
        },
        {
            "symbolicName":"org.psem2m.isolates.monitor"
        }
    ]
}