{
    "name":"DemoPython",
    "components":[
        {
            "name":"sensor-1",
            "type":"Sensor",
            "properties":{
                "sensor.id":"sensor-demo-1"
            }
        },
        {
            "name":"listener-1",
            "type":"SensorListener",
            "properties":{
                "max_lines":20
            }
        }
    ]
}
